version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
      - unzip -o packer.zip
      - mv packer /usr/local/bin/packer
      - chmod +x /usr/local/bin/packer
  pre_build:
    commands:
      - echo "Validating Template..."
      - packer init . # Initialize plugins if using HCL
      - packer validate .
  build:
    commands:
      - echo "Building AMI..."
      - packer build .
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'